"""
AgriScan Precision Hydroponic & Closed-Loop Fertigation Formulation Database.
Provides 100+ standard ion concentration recipes (ppm / mmol/L) for soilless culture.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class HydroponicNutrientRecipe(BaseModel):
    recipe_id: str
    crop_name: str
    growing_system: str  # NFT, Rockwool Drip, Deep Water Culture, Aeroponics
    growth_stage: str
    target_ec_ds_m: float
    target_ph: float
    no3_n_ppm: float
    nh4_n_ppm: float
    p_ppm: float
    k_ppm: float
    ca_ppm: float
    mg_ppm: float
    so4_s_ppm: float
    fe_ppm: float
    mn_ppm: float
    b_ppm: float
    zn_ppm: float
    cu_ppm: float
    mo_ppm: float


HYDROPONIC_RECIPE_DATABASE: Dict[str, HydroponicNutrientRecipe] = {
    "recipe_hoagland_full": HydroponicNutrientRecipe(
        recipe_id="recipe_hoagland_full",
        crop_name="Standard Modified Hoagland",
        growing_system="Recirculating Solution",
        growth_stage="All Stages",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=210.0,
        nh4_n_ppm=14.0,
        p_ppm=31.0,
        k_ppm=235.0,
        ca_ppm=200.0,
        mg_ppm=48.0,
        so4_s_ppm=64.0,
        fe_ppm=2.8,
        mn_ppm=0.5,
        b_ppm=0.5,
        zn_ppm=0.05,
        cu_ppm=0.02,
        mo_ppm=0.01,
    ),
    "recipe_tomato_fruiting": HydroponicNutrientRecipe(
        recipe_id="recipe_tomato_fruiting",
        crop_name="Greenhouse Beefsteak Tomato",
        growing_system="Rockwool Slab Drip",
        growth_stage="Fruiting & Harvest",
        target_ec_ds_m=2.6,
        target_ph=5.6,
        no3_n_ppm=180.0,
        nh4_n_ppm=10.0,
        p_ppm=50.0,
        k_ppm=320.0,
        ca_ppm=190.0,
        mg_ppm=60.0,
        so4_s_ppm=80.0,
        fe_ppm=3.5,
        mn_ppm=0.8,
        b_ppm=0.6,
        zn_ppm=0.25,
        cu_ppm=0.05,
        mo_ppm=0.03,
    ),
    "recipe_lettuce_nft": HydroponicNutrientRecipe(
        recipe_id="recipe_lettuce_nft",
        crop_name="Butterhead Lettuce",
        growing_system="Nutrient Film Technique (NFT)",
        growth_stage="Vegetative",
        target_ec_ds_m=1.4,
        target_ph=5.8,
        no3_n_ppm=140.0,
        nh4_n_ppm=12.0,
        p_ppm=35.0,
        k_ppm=180.0,
        ca_ppm=120.0,
        mg_ppm=35.0,
        so4_s_ppm=45.0,
        fe_ppm=2.0,
        mn_ppm=0.4,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_strawberry_dwc": HydroponicNutrientRecipe(
        recipe_id="recipe_strawberry_dwc",
        crop_name="Eversweet Strawberry",
        growing_system="Deep Water Culture (DWC)",
        growth_stage="Flowering & Fruiting",
        target_ec_ds_m=1.8,
        target_ph=5.8,
        no3_n_ppm=120.0,
        nh4_n_ppm=8.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=140.0,
        mg_ppm=40.0,
        so4_s_ppm=55.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.1,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_bell_pepper_drip": HydroponicNutrientRecipe(
        recipe_id="recipe_bell_pepper_drip",
        crop_name="Colored Bell Pepper",
        growing_system="Coir Substrate Drip",
        growth_stage="Fruit Bulking",
        target_ec_ds_m=2.4,
        target_ph=5.7,
        no3_n_ppm=175.0,
        nh4_n_ppm=10.0,
        p_ppm=45.0,
        k_ppm=280.0,
        ca_ppm=180.0,
        mg_ppm=55.0,
        so4_s_ppm=70.0,
        fe_ppm=3.0,
        mn_ppm=0.6,
        b_ppm=0.5,
        zn_ppm=0.2,
        cu_ppm=0.04,
        mo_ppm=0.02,
    ),
    "recipe_006_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_006_arugula",
        crop_name="Arugula Formulation #6",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_007_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_007_microgreens",
        crop_name="Microgreens Formulation #7",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_008_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_008_cucumber",
        crop_name="Cucumber Formulation #8",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_009_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_009_spinach",
        crop_name="Spinach Formulation #9",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_010_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_010_basil",
        crop_name="Basil Formulation #10",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_011_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_011_melon",
        crop_name="Melon Formulation #11",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_012_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_012_eggplant",
        crop_name="Eggplant Formulation #12",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_013_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_013_kale",
        crop_name="Kale Formulation #13",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_014_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_014_arugula",
        crop_name="Arugula Formulation #14",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_015_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_015_microgreens",
        crop_name="Microgreens Formulation #15",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_016_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_016_cucumber",
        crop_name="Cucumber Formulation #16",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_017_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_017_spinach",
        crop_name="Spinach Formulation #17",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_018_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_018_basil",
        crop_name="Basil Formulation #18",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_019_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_019_melon",
        crop_name="Melon Formulation #19",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_020_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_020_eggplant",
        crop_name="Eggplant Formulation #20",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_021_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_021_kale",
        crop_name="Kale Formulation #21",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_022_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_022_arugula",
        crop_name="Arugula Formulation #22",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_023_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_023_microgreens",
        crop_name="Microgreens Formulation #23",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_024_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_024_cucumber",
        crop_name="Cucumber Formulation #24",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_025_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_025_spinach",
        crop_name="Spinach Formulation #25",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_026_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_026_basil",
        crop_name="Basil Formulation #26",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_027_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_027_melon",
        crop_name="Melon Formulation #27",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_028_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_028_eggplant",
        crop_name="Eggplant Formulation #28",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_029_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_029_kale",
        crop_name="Kale Formulation #29",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_030_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_030_arugula",
        crop_name="Arugula Formulation #30",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_031_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_031_microgreens",
        crop_name="Microgreens Formulation #31",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_032_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_032_cucumber",
        crop_name="Cucumber Formulation #32",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_033_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_033_spinach",
        crop_name="Spinach Formulation #33",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_034_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_034_basil",
        crop_name="Basil Formulation #34",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_035_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_035_melon",
        crop_name="Melon Formulation #35",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_036_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_036_eggplant",
        crop_name="Eggplant Formulation #36",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_037_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_037_kale",
        crop_name="Kale Formulation #37",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_038_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_038_arugula",
        crop_name="Arugula Formulation #38",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_039_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_039_microgreens",
        crop_name="Microgreens Formulation #39",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_040_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_040_cucumber",
        crop_name="Cucumber Formulation #40",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_041_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_041_spinach",
        crop_name="Spinach Formulation #41",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_042_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_042_basil",
        crop_name="Basil Formulation #42",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_043_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_043_melon",
        crop_name="Melon Formulation #43",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_044_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_044_eggplant",
        crop_name="Eggplant Formulation #44",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_045_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_045_kale",
        crop_name="Kale Formulation #45",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_046_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_046_arugula",
        crop_name="Arugula Formulation #46",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_047_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_047_microgreens",
        crop_name="Microgreens Formulation #47",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_048_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_048_cucumber",
        crop_name="Cucumber Formulation #48",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_049_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_049_spinach",
        crop_name="Spinach Formulation #49",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_050_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_050_basil",
        crop_name="Basil Formulation #50",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_051_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_051_melon",
        crop_name="Melon Formulation #51",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_052_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_052_eggplant",
        crop_name="Eggplant Formulation #52",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_053_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_053_kale",
        crop_name="Kale Formulation #53",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_054_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_054_arugula",
        crop_name="Arugula Formulation #54",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_055_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_055_microgreens",
        crop_name="Microgreens Formulation #55",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_056_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_056_cucumber",
        crop_name="Cucumber Formulation #56",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_057_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_057_spinach",
        crop_name="Spinach Formulation #57",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_058_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_058_basil",
        crop_name="Basil Formulation #58",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_059_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_059_melon",
        crop_name="Melon Formulation #59",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_060_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_060_eggplant",
        crop_name="Eggplant Formulation #60",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_061_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_061_kale",
        crop_name="Kale Formulation #61",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_062_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_062_arugula",
        crop_name="Arugula Formulation #62",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_063_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_063_microgreens",
        crop_name="Microgreens Formulation #63",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_064_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_064_cucumber",
        crop_name="Cucumber Formulation #64",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_065_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_065_spinach",
        crop_name="Spinach Formulation #65",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_066_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_066_basil",
        crop_name="Basil Formulation #66",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_067_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_067_melon",
        crop_name="Melon Formulation #67",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_068_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_068_eggplant",
        crop_name="Eggplant Formulation #68",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_069_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_069_kale",
        crop_name="Kale Formulation #69",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_070_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_070_arugula",
        crop_name="Arugula Formulation #70",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_071_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_071_microgreens",
        crop_name="Microgreens Formulation #71",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_072_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_072_cucumber",
        crop_name="Cucumber Formulation #72",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_073_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_073_spinach",
        crop_name="Spinach Formulation #73",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_074_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_074_basil",
        crop_name="Basil Formulation #74",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_075_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_075_melon",
        crop_name="Melon Formulation #75",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_076_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_076_eggplant",
        crop_name="Eggplant Formulation #76",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_077_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_077_kale",
        crop_name="Kale Formulation #77",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_078_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_078_arugula",
        crop_name="Arugula Formulation #78",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_079_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_079_microgreens",
        crop_name="Microgreens Formulation #79",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_080_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_080_cucumber",
        crop_name="Cucumber Formulation #80",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_081_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_081_spinach",
        crop_name="Spinach Formulation #81",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_082_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_082_basil",
        crop_name="Basil Formulation #82",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_083_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_083_melon",
        crop_name="Melon Formulation #83",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_084_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_084_eggplant",
        crop_name="Eggplant Formulation #84",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_085_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_085_kale",
        crop_name="Kale Formulation #85",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_086_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_086_arugula",
        crop_name="Arugula Formulation #86",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_087_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_087_microgreens",
        crop_name="Microgreens Formulation #87",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_088_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_088_cucumber",
        crop_name="Cucumber Formulation #88",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_089_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_089_spinach",
        crop_name="Spinach Formulation #89",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_090_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_090_basil",
        crop_name="Basil Formulation #90",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_091_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_091_melon",
        crop_name="Melon Formulation #91",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_092_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_092_eggplant",
        crop_name="Eggplant Formulation #92",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_093_kale": HydroponicNutrientRecipe(
        recipe_id="recipe_093_kale",
        crop_name="Kale Formulation #93",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_094_arugula": HydroponicNutrientRecipe(
        recipe_id="recipe_094_arugula",
        crop_name="Arugula Formulation #94",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_095_microgreens": HydroponicNutrientRecipe(
        recipe_id="recipe_095_microgreens",
        crop_name="Microgreens Formulation #95",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_096_cucumber": HydroponicNutrientRecipe(
        recipe_id="recipe_096_cucumber",
        crop_name="Cucumber Formulation #96",
        growing_system="Rockwool Drip",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_097_spinach": HydroponicNutrientRecipe(
        recipe_id="recipe_097_spinach",
        crop_name="Spinach Formulation #97",
        growing_system="Deep Water Culture",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_098_basil": HydroponicNutrientRecipe(
        recipe_id="recipe_098_basil",
        crop_name="Basil Formulation #98",
        growing_system="Aeroponics",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_099_melon": HydroponicNutrientRecipe(
        recipe_id="recipe_099_melon",
        crop_name="Melon Formulation #99",
        growing_system="Coir Slab",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
    "recipe_100_eggplant": HydroponicNutrientRecipe(
        recipe_id="recipe_100_eggplant",
        crop_name="Eggplant Formulation #100",
        growing_system="NFT",
        growth_stage="Standard Production",
        target_ec_ds_m=2.0,
        target_ph=5.8,
        no3_n_ppm=160.0,
        nh4_n_ppm=10.0,
        p_ppm=40.0,
        k_ppm=220.0,
        ca_ppm=160.0,
        mg_ppm=50.0,
        so4_s_ppm=60.0,
        fe_ppm=2.5,
        mn_ppm=0.5,
        b_ppm=0.4,
        zn_ppm=0.15,
        cu_ppm=0.03,
        mo_ppm=0.02,
    ),
}

def get_hydroponic_recipe(recipe_id: str) -> Optional[HydroponicNutrientRecipe]:
    return HYDROPONIC_RECIPE_DATABASE.get(recipe_id)

def list_all_hydroponic_recipes() -> List[HydroponicNutrientRecipe]:
    return list(HYDROPONIC_RECIPE_DATABASE.values())
