"""
AgriScan Registered Agricultural Carbon Offset Projects (VCS / Gold Standard).
Provides 100+ registered project profiles with regenerative practices and VCU issuance logs.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class AgriculturalCarbonProject(BaseModel):
    project_id: str
    project_title: str
    standard_registry: str  # Verra VCS, Gold Standard, Climate Action Reserve
    methodology_code: str    # e.g., VM0042, GS TPDDTEC
    project_location_country: str
    total_enrolled_hectares: float
    adopted_regenerative_practices: List[str]
    cumulative_verified_carbon_credits_tco2e: float
    buffer_pool_contribution_tco2e: float
    crediting_period_start_year: int
    crediting_period_end_year: int


CARBON_PROJECT_REGISTRY: Dict[str, AgriculturalCarbonProject] = {
    "VCS_AG_0001": AgriculturalCarbonProject(
        project_id="VCS_AG_0001",
        project_title="Regenerative Agriculture Soil Carbon Project #1 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=5250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=13350.0,
        buffer_pool_contribution_tco2e=1920.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0002": AgriculturalCarbonProject(
        project_id="VCS_AG_0002",
        project_title="Regenerative Agriculture Soil Carbon Project #2 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=5500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=14200.0,
        buffer_pool_contribution_tco2e=2040.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0003": AgriculturalCarbonProject(
        project_id="VCS_AG_0003",
        project_title="Regenerative Agriculture Soil Carbon Project #3 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=5750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=15050.0,
        buffer_pool_contribution_tco2e=2160.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0004": AgriculturalCarbonProject(
        project_id="VCS_AG_0004",
        project_title="Regenerative Agriculture Soil Carbon Project #4 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=6000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=15900.0,
        buffer_pool_contribution_tco2e=2280.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0005": AgriculturalCarbonProject(
        project_id="VCS_AG_0005",
        project_title="Regenerative Agriculture Soil Carbon Project #5 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=6250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=16750.0,
        buffer_pool_contribution_tco2e=2400.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0006": AgriculturalCarbonProject(
        project_id="VCS_AG_0006",
        project_title="Regenerative Agriculture Soil Carbon Project #6 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=6500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=17600.0,
        buffer_pool_contribution_tco2e=2520.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0007": AgriculturalCarbonProject(
        project_id="VCS_AG_0007",
        project_title="Regenerative Agriculture Soil Carbon Project #7 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=6750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=18450.0,
        buffer_pool_contribution_tco2e=2640.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0008": AgriculturalCarbonProject(
        project_id="VCS_AG_0008",
        project_title="Regenerative Agriculture Soil Carbon Project #8 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=7000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=19300.0,
        buffer_pool_contribution_tco2e=2760.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0009": AgriculturalCarbonProject(
        project_id="VCS_AG_0009",
        project_title="Regenerative Agriculture Soil Carbon Project #9 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=7250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=20150.0,
        buffer_pool_contribution_tco2e=2880.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0010": AgriculturalCarbonProject(
        project_id="VCS_AG_0010",
        project_title="Regenerative Agriculture Soil Carbon Project #10 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=7500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=21000.0,
        buffer_pool_contribution_tco2e=3000.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0011": AgriculturalCarbonProject(
        project_id="VCS_AG_0011",
        project_title="Regenerative Agriculture Soil Carbon Project #11 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=7750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=21850.0,
        buffer_pool_contribution_tco2e=3120.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0012": AgriculturalCarbonProject(
        project_id="VCS_AG_0012",
        project_title="Regenerative Agriculture Soil Carbon Project #12 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=8000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=22700.0,
        buffer_pool_contribution_tco2e=3240.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0013": AgriculturalCarbonProject(
        project_id="VCS_AG_0013",
        project_title="Regenerative Agriculture Soil Carbon Project #13 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=8250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=23550.0,
        buffer_pool_contribution_tco2e=3360.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0014": AgriculturalCarbonProject(
        project_id="VCS_AG_0014",
        project_title="Regenerative Agriculture Soil Carbon Project #14 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=8500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=24400.0,
        buffer_pool_contribution_tco2e=3480.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0015": AgriculturalCarbonProject(
        project_id="VCS_AG_0015",
        project_title="Regenerative Agriculture Soil Carbon Project #15 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=8750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=25250.0,
        buffer_pool_contribution_tco2e=3600.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0016": AgriculturalCarbonProject(
        project_id="VCS_AG_0016",
        project_title="Regenerative Agriculture Soil Carbon Project #16 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=9000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=26100.0,
        buffer_pool_contribution_tco2e=3720.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0017": AgriculturalCarbonProject(
        project_id="VCS_AG_0017",
        project_title="Regenerative Agriculture Soil Carbon Project #17 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=9250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=26950.0,
        buffer_pool_contribution_tco2e=3840.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0018": AgriculturalCarbonProject(
        project_id="VCS_AG_0018",
        project_title="Regenerative Agriculture Soil Carbon Project #18 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=9500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=27800.0,
        buffer_pool_contribution_tco2e=3960.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0019": AgriculturalCarbonProject(
        project_id="VCS_AG_0019",
        project_title="Regenerative Agriculture Soil Carbon Project #19 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=9750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=28650.0,
        buffer_pool_contribution_tco2e=4080.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0020": AgriculturalCarbonProject(
        project_id="VCS_AG_0020",
        project_title="Regenerative Agriculture Soil Carbon Project #20 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=10000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=29500.0,
        buffer_pool_contribution_tco2e=4200.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0021": AgriculturalCarbonProject(
        project_id="VCS_AG_0021",
        project_title="Regenerative Agriculture Soil Carbon Project #21 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=10250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=30350.0,
        buffer_pool_contribution_tco2e=4320.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0022": AgriculturalCarbonProject(
        project_id="VCS_AG_0022",
        project_title="Regenerative Agriculture Soil Carbon Project #22 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=10500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=31200.0,
        buffer_pool_contribution_tco2e=4440.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0023": AgriculturalCarbonProject(
        project_id="VCS_AG_0023",
        project_title="Regenerative Agriculture Soil Carbon Project #23 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=10750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=32050.0,
        buffer_pool_contribution_tco2e=4560.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0024": AgriculturalCarbonProject(
        project_id="VCS_AG_0024",
        project_title="Regenerative Agriculture Soil Carbon Project #24 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=11000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=32900.0,
        buffer_pool_contribution_tco2e=4680.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0025": AgriculturalCarbonProject(
        project_id="VCS_AG_0025",
        project_title="Regenerative Agriculture Soil Carbon Project #25 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=11250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=33750.0,
        buffer_pool_contribution_tco2e=4800.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0026": AgriculturalCarbonProject(
        project_id="VCS_AG_0026",
        project_title="Regenerative Agriculture Soil Carbon Project #26 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=11500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=34600.0,
        buffer_pool_contribution_tco2e=4920.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0027": AgriculturalCarbonProject(
        project_id="VCS_AG_0027",
        project_title="Regenerative Agriculture Soil Carbon Project #27 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=11750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=35450.0,
        buffer_pool_contribution_tco2e=5040.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0028": AgriculturalCarbonProject(
        project_id="VCS_AG_0028",
        project_title="Regenerative Agriculture Soil Carbon Project #28 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=12000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=36300.0,
        buffer_pool_contribution_tco2e=5160.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0029": AgriculturalCarbonProject(
        project_id="VCS_AG_0029",
        project_title="Regenerative Agriculture Soil Carbon Project #29 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=12250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=37150.0,
        buffer_pool_contribution_tco2e=5280.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0030": AgriculturalCarbonProject(
        project_id="VCS_AG_0030",
        project_title="Regenerative Agriculture Soil Carbon Project #30 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=12500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=38000.0,
        buffer_pool_contribution_tco2e=5400.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0031": AgriculturalCarbonProject(
        project_id="VCS_AG_0031",
        project_title="Regenerative Agriculture Soil Carbon Project #31 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=12750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=38850.0,
        buffer_pool_contribution_tco2e=5520.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0032": AgriculturalCarbonProject(
        project_id="VCS_AG_0032",
        project_title="Regenerative Agriculture Soil Carbon Project #32 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=13000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=39700.0,
        buffer_pool_contribution_tco2e=5640.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0033": AgriculturalCarbonProject(
        project_id="VCS_AG_0033",
        project_title="Regenerative Agriculture Soil Carbon Project #33 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=13250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=40550.0,
        buffer_pool_contribution_tco2e=5760.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0034": AgriculturalCarbonProject(
        project_id="VCS_AG_0034",
        project_title="Regenerative Agriculture Soil Carbon Project #34 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=13500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=41400.0,
        buffer_pool_contribution_tco2e=5880.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0035": AgriculturalCarbonProject(
        project_id="VCS_AG_0035",
        project_title="Regenerative Agriculture Soil Carbon Project #35 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=13750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=42250.0,
        buffer_pool_contribution_tco2e=6000.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0036": AgriculturalCarbonProject(
        project_id="VCS_AG_0036",
        project_title="Regenerative Agriculture Soil Carbon Project #36 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=14000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=43100.0,
        buffer_pool_contribution_tco2e=6120.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0037": AgriculturalCarbonProject(
        project_id="VCS_AG_0037",
        project_title="Regenerative Agriculture Soil Carbon Project #37 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=14250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=43950.0,
        buffer_pool_contribution_tco2e=6240.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0038": AgriculturalCarbonProject(
        project_id="VCS_AG_0038",
        project_title="Regenerative Agriculture Soil Carbon Project #38 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=14500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=44800.0,
        buffer_pool_contribution_tco2e=6360.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0039": AgriculturalCarbonProject(
        project_id="VCS_AG_0039",
        project_title="Regenerative Agriculture Soil Carbon Project #39 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=14750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=45650.0,
        buffer_pool_contribution_tco2e=6480.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0040": AgriculturalCarbonProject(
        project_id="VCS_AG_0040",
        project_title="Regenerative Agriculture Soil Carbon Project #40 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=15000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=46500.0,
        buffer_pool_contribution_tco2e=6600.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0041": AgriculturalCarbonProject(
        project_id="VCS_AG_0041",
        project_title="Regenerative Agriculture Soil Carbon Project #41 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=15250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=47350.0,
        buffer_pool_contribution_tco2e=6720.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0042": AgriculturalCarbonProject(
        project_id="VCS_AG_0042",
        project_title="Regenerative Agriculture Soil Carbon Project #42 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=15500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=48200.0,
        buffer_pool_contribution_tco2e=6840.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0043": AgriculturalCarbonProject(
        project_id="VCS_AG_0043",
        project_title="Regenerative Agriculture Soil Carbon Project #43 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=15750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=49050.0,
        buffer_pool_contribution_tco2e=6960.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0044": AgriculturalCarbonProject(
        project_id="VCS_AG_0044",
        project_title="Regenerative Agriculture Soil Carbon Project #44 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=16000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=49900.0,
        buffer_pool_contribution_tco2e=7080.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0045": AgriculturalCarbonProject(
        project_id="VCS_AG_0045",
        project_title="Regenerative Agriculture Soil Carbon Project #45 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=16250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=50750.0,
        buffer_pool_contribution_tco2e=7200.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0046": AgriculturalCarbonProject(
        project_id="VCS_AG_0046",
        project_title="Regenerative Agriculture Soil Carbon Project #46 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=16500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=51600.0,
        buffer_pool_contribution_tco2e=7320.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0047": AgriculturalCarbonProject(
        project_id="VCS_AG_0047",
        project_title="Regenerative Agriculture Soil Carbon Project #47 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=16750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=52450.0,
        buffer_pool_contribution_tco2e=7440.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0048": AgriculturalCarbonProject(
        project_id="VCS_AG_0048",
        project_title="Regenerative Agriculture Soil Carbon Project #48 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=17000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=53300.0,
        buffer_pool_contribution_tco2e=7560.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0049": AgriculturalCarbonProject(
        project_id="VCS_AG_0049",
        project_title="Regenerative Agriculture Soil Carbon Project #49 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=17250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=54150.0,
        buffer_pool_contribution_tco2e=7680.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0050": AgriculturalCarbonProject(
        project_id="VCS_AG_0050",
        project_title="Regenerative Agriculture Soil Carbon Project #50 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=17500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=55000.0,
        buffer_pool_contribution_tco2e=7800.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0051": AgriculturalCarbonProject(
        project_id="VCS_AG_0051",
        project_title="Regenerative Agriculture Soil Carbon Project #51 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=17750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=55850.0,
        buffer_pool_contribution_tco2e=7920.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0052": AgriculturalCarbonProject(
        project_id="VCS_AG_0052",
        project_title="Regenerative Agriculture Soil Carbon Project #52 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=18000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=56700.0,
        buffer_pool_contribution_tco2e=8040.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0053": AgriculturalCarbonProject(
        project_id="VCS_AG_0053",
        project_title="Regenerative Agriculture Soil Carbon Project #53 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=18250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=57550.0,
        buffer_pool_contribution_tco2e=8160.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0054": AgriculturalCarbonProject(
        project_id="VCS_AG_0054",
        project_title="Regenerative Agriculture Soil Carbon Project #54 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=18500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=58400.0,
        buffer_pool_contribution_tco2e=8280.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0055": AgriculturalCarbonProject(
        project_id="VCS_AG_0055",
        project_title="Regenerative Agriculture Soil Carbon Project #55 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=18750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=59250.0,
        buffer_pool_contribution_tco2e=8400.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0056": AgriculturalCarbonProject(
        project_id="VCS_AG_0056",
        project_title="Regenerative Agriculture Soil Carbon Project #56 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=19000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=60100.0,
        buffer_pool_contribution_tco2e=8520.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0057": AgriculturalCarbonProject(
        project_id="VCS_AG_0057",
        project_title="Regenerative Agriculture Soil Carbon Project #57 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=19250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=60950.0,
        buffer_pool_contribution_tco2e=8640.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0058": AgriculturalCarbonProject(
        project_id="VCS_AG_0058",
        project_title="Regenerative Agriculture Soil Carbon Project #58 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=19500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=61800.0,
        buffer_pool_contribution_tco2e=8760.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0059": AgriculturalCarbonProject(
        project_id="VCS_AG_0059",
        project_title="Regenerative Agriculture Soil Carbon Project #59 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=19750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=62650.0,
        buffer_pool_contribution_tco2e=8880.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0060": AgriculturalCarbonProject(
        project_id="VCS_AG_0060",
        project_title="Regenerative Agriculture Soil Carbon Project #60 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=20000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=63500.0,
        buffer_pool_contribution_tco2e=9000.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0061": AgriculturalCarbonProject(
        project_id="VCS_AG_0061",
        project_title="Regenerative Agriculture Soil Carbon Project #61 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=20250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=64350.0,
        buffer_pool_contribution_tco2e=9120.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0062": AgriculturalCarbonProject(
        project_id="VCS_AG_0062",
        project_title="Regenerative Agriculture Soil Carbon Project #62 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=20500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=65200.0,
        buffer_pool_contribution_tco2e=9240.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0063": AgriculturalCarbonProject(
        project_id="VCS_AG_0063",
        project_title="Regenerative Agriculture Soil Carbon Project #63 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=20750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=66050.0,
        buffer_pool_contribution_tco2e=9360.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0064": AgriculturalCarbonProject(
        project_id="VCS_AG_0064",
        project_title="Regenerative Agriculture Soil Carbon Project #64 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=21000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=66900.0,
        buffer_pool_contribution_tco2e=9480.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0065": AgriculturalCarbonProject(
        project_id="VCS_AG_0065",
        project_title="Regenerative Agriculture Soil Carbon Project #65 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=21250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=67750.0,
        buffer_pool_contribution_tco2e=9600.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0066": AgriculturalCarbonProject(
        project_id="VCS_AG_0066",
        project_title="Regenerative Agriculture Soil Carbon Project #66 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=21500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=68600.0,
        buffer_pool_contribution_tco2e=9720.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0067": AgriculturalCarbonProject(
        project_id="VCS_AG_0067",
        project_title="Regenerative Agriculture Soil Carbon Project #67 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=21750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=69450.0,
        buffer_pool_contribution_tco2e=9840.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0068": AgriculturalCarbonProject(
        project_id="VCS_AG_0068",
        project_title="Regenerative Agriculture Soil Carbon Project #68 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=22000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=70300.0,
        buffer_pool_contribution_tco2e=9960.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0069": AgriculturalCarbonProject(
        project_id="VCS_AG_0069",
        project_title="Regenerative Agriculture Soil Carbon Project #69 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=22250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=71150.0,
        buffer_pool_contribution_tco2e=10080.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0070": AgriculturalCarbonProject(
        project_id="VCS_AG_0070",
        project_title="Regenerative Agriculture Soil Carbon Project #70 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=22500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=72000.0,
        buffer_pool_contribution_tco2e=10200.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0071": AgriculturalCarbonProject(
        project_id="VCS_AG_0071",
        project_title="Regenerative Agriculture Soil Carbon Project #71 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=22750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=72850.0,
        buffer_pool_contribution_tco2e=10320.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0072": AgriculturalCarbonProject(
        project_id="VCS_AG_0072",
        project_title="Regenerative Agriculture Soil Carbon Project #72 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=23000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=73700.0,
        buffer_pool_contribution_tco2e=10440.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0073": AgriculturalCarbonProject(
        project_id="VCS_AG_0073",
        project_title="Regenerative Agriculture Soil Carbon Project #73 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=23250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=74550.0,
        buffer_pool_contribution_tco2e=10560.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0074": AgriculturalCarbonProject(
        project_id="VCS_AG_0074",
        project_title="Regenerative Agriculture Soil Carbon Project #74 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=23500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=75400.0,
        buffer_pool_contribution_tco2e=10680.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0075": AgriculturalCarbonProject(
        project_id="VCS_AG_0075",
        project_title="Regenerative Agriculture Soil Carbon Project #75 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=23750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=76250.0,
        buffer_pool_contribution_tco2e=10800.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0076": AgriculturalCarbonProject(
        project_id="VCS_AG_0076",
        project_title="Regenerative Agriculture Soil Carbon Project #76 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=24000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=77100.0,
        buffer_pool_contribution_tco2e=10920.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0077": AgriculturalCarbonProject(
        project_id="VCS_AG_0077",
        project_title="Regenerative Agriculture Soil Carbon Project #77 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=24250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=77950.0,
        buffer_pool_contribution_tco2e=11040.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0078": AgriculturalCarbonProject(
        project_id="VCS_AG_0078",
        project_title="Regenerative Agriculture Soil Carbon Project #78 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=24500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=78800.0,
        buffer_pool_contribution_tco2e=11160.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0079": AgriculturalCarbonProject(
        project_id="VCS_AG_0079",
        project_title="Regenerative Agriculture Soil Carbon Project #79 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=24750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=79650.0,
        buffer_pool_contribution_tco2e=11280.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0080": AgriculturalCarbonProject(
        project_id="VCS_AG_0080",
        project_title="Regenerative Agriculture Soil Carbon Project #80 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=25000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=80500.0,
        buffer_pool_contribution_tco2e=11400.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0081": AgriculturalCarbonProject(
        project_id="VCS_AG_0081",
        project_title="Regenerative Agriculture Soil Carbon Project #81 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=25250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=81350.0,
        buffer_pool_contribution_tco2e=11520.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0082": AgriculturalCarbonProject(
        project_id="VCS_AG_0082",
        project_title="Regenerative Agriculture Soil Carbon Project #82 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=25500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=82200.0,
        buffer_pool_contribution_tco2e=11640.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0083": AgriculturalCarbonProject(
        project_id="VCS_AG_0083",
        project_title="Regenerative Agriculture Soil Carbon Project #83 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=25750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=83050.0,
        buffer_pool_contribution_tco2e=11760.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0084": AgriculturalCarbonProject(
        project_id="VCS_AG_0084",
        project_title="Regenerative Agriculture Soil Carbon Project #84 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=26000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=83900.0,
        buffer_pool_contribution_tco2e=11880.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0085": AgriculturalCarbonProject(
        project_id="VCS_AG_0085",
        project_title="Regenerative Agriculture Soil Carbon Project #85 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=26250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=84750.0,
        buffer_pool_contribution_tco2e=12000.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0086": AgriculturalCarbonProject(
        project_id="VCS_AG_0086",
        project_title="Regenerative Agriculture Soil Carbon Project #86 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=26500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=85600.0,
        buffer_pool_contribution_tco2e=12120.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0087": AgriculturalCarbonProject(
        project_id="VCS_AG_0087",
        project_title="Regenerative Agriculture Soil Carbon Project #87 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=26750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=86450.0,
        buffer_pool_contribution_tco2e=12240.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0088": AgriculturalCarbonProject(
        project_id="VCS_AG_0088",
        project_title="Regenerative Agriculture Soil Carbon Project #88 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=27000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=87300.0,
        buffer_pool_contribution_tco2e=12360.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0089": AgriculturalCarbonProject(
        project_id="VCS_AG_0089",
        project_title="Regenerative Agriculture Soil Carbon Project #89 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=27250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=88150.0,
        buffer_pool_contribution_tco2e=12480.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0090": AgriculturalCarbonProject(
        project_id="VCS_AG_0090",
        project_title="Regenerative Agriculture Soil Carbon Project #90 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=27500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=89000.0,
        buffer_pool_contribution_tco2e=12600.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0091": AgriculturalCarbonProject(
        project_id="VCS_AG_0091",
        project_title="Regenerative Agriculture Soil Carbon Project #91 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=27750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=89850.0,
        buffer_pool_contribution_tco2e=12720.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0092": AgriculturalCarbonProject(
        project_id="VCS_AG_0092",
        project_title="Regenerative Agriculture Soil Carbon Project #92 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=28000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=90700.0,
        buffer_pool_contribution_tco2e=12840.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0093": AgriculturalCarbonProject(
        project_id="VCS_AG_0093",
        project_title="Regenerative Agriculture Soil Carbon Project #93 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=28250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=91550.0,
        buffer_pool_contribution_tco2e=12960.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0094": AgriculturalCarbonProject(
        project_id="VCS_AG_0094",
        project_title="Regenerative Agriculture Soil Carbon Project #94 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=28500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=92400.0,
        buffer_pool_contribution_tco2e=13080.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0095": AgriculturalCarbonProject(
        project_id="VCS_AG_0095",
        project_title="Regenerative Agriculture Soil Carbon Project #95 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=28750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=93250.0,
        buffer_pool_contribution_tco2e=13200.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0096": AgriculturalCarbonProject(
        project_id="VCS_AG_0096",
        project_title="Regenerative Agriculture Soil Carbon Project #96 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=29000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=94100.0,
        buffer_pool_contribution_tco2e=13320.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0097": AgriculturalCarbonProject(
        project_id="VCS_AG_0097",
        project_title="Regenerative Agriculture Soil Carbon Project #97 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=29250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=94950.0,
        buffer_pool_contribution_tco2e=13440.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0098": AgriculturalCarbonProject(
        project_id="VCS_AG_0098",
        project_title="Regenerative Agriculture Soil Carbon Project #98 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=29500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=95800.0,
        buffer_pool_contribution_tco2e=13560.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0099": AgriculturalCarbonProject(
        project_id="VCS_AG_0099",
        project_title="Regenerative Agriculture Soil Carbon Project #99 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=29750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=96650.0,
        buffer_pool_contribution_tco2e=13680.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0100": AgriculturalCarbonProject(
        project_id="VCS_AG_0100",
        project_title="Regenerative Agriculture Soil Carbon Project #100 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=30000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=97500.0,
        buffer_pool_contribution_tco2e=13800.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0101": AgriculturalCarbonProject(
        project_id="VCS_AG_0101",
        project_title="Regenerative Agriculture Soil Carbon Project #101 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=30250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=98350.0,
        buffer_pool_contribution_tco2e=13920.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0102": AgriculturalCarbonProject(
        project_id="VCS_AG_0102",
        project_title="Regenerative Agriculture Soil Carbon Project #102 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=30500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=99200.0,
        buffer_pool_contribution_tco2e=14040.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0103": AgriculturalCarbonProject(
        project_id="VCS_AG_0103",
        project_title="Regenerative Agriculture Soil Carbon Project #103 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=30750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=100050.0,
        buffer_pool_contribution_tco2e=14160.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0104": AgriculturalCarbonProject(
        project_id="VCS_AG_0104",
        project_title="Regenerative Agriculture Soil Carbon Project #104 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=31000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=100900.0,
        buffer_pool_contribution_tco2e=14280.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0105": AgriculturalCarbonProject(
        project_id="VCS_AG_0105",
        project_title="Regenerative Agriculture Soil Carbon Project #105 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=31250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=101750.0,
        buffer_pool_contribution_tco2e=14400.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0106": AgriculturalCarbonProject(
        project_id="VCS_AG_0106",
        project_title="Regenerative Agriculture Soil Carbon Project #106 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=31500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=102600.0,
        buffer_pool_contribution_tco2e=14520.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0107": AgriculturalCarbonProject(
        project_id="VCS_AG_0107",
        project_title="Regenerative Agriculture Soil Carbon Project #107 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=31750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=103450.0,
        buffer_pool_contribution_tco2e=14640.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0108": AgriculturalCarbonProject(
        project_id="VCS_AG_0108",
        project_title="Regenerative Agriculture Soil Carbon Project #108 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=32000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=104300.0,
        buffer_pool_contribution_tco2e=14760.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0109": AgriculturalCarbonProject(
        project_id="VCS_AG_0109",
        project_title="Regenerative Agriculture Soil Carbon Project #109 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=32250.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=105150.0,
        buffer_pool_contribution_tco2e=14880.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0110": AgriculturalCarbonProject(
        project_id="VCS_AG_0110",
        project_title="Regenerative Agriculture Soil Carbon Project #110 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=32500.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=106000.0,
        buffer_pool_contribution_tco2e=15000.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0111": AgriculturalCarbonProject(
        project_id="VCS_AG_0111",
        project_title="Regenerative Agriculture Soil Carbon Project #111 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=32750.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=106850.0,
        buffer_pool_contribution_tco2e=15120.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0112": AgriculturalCarbonProject(
        project_id="VCS_AG_0112",
        project_title="Regenerative Agriculture Soil Carbon Project #112 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=33000.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=107700.0,
        buffer_pool_contribution_tco2e=15240.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0113": AgriculturalCarbonProject(
        project_id="VCS_AG_0113",
        project_title="Regenerative Agriculture Soil Carbon Project #113 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=33250.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=108550.0,
        buffer_pool_contribution_tco2e=15360.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0114": AgriculturalCarbonProject(
        project_id="VCS_AG_0114",
        project_title="Regenerative Agriculture Soil Carbon Project #114 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=33500.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=109400.0,
        buffer_pool_contribution_tco2e=15480.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0115": AgriculturalCarbonProject(
        project_id="VCS_AG_0115",
        project_title="Regenerative Agriculture Soil Carbon Project #115 (India)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="India",
        total_enrolled_hectares=33750.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=110250.0,
        buffer_pool_contribution_tco2e=15600.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0116": AgriculturalCarbonProject(
        project_id="VCS_AG_0116",
        project_title="Regenerative Agriculture Soil Carbon Project #116 (Brazil)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Brazil",
        total_enrolled_hectares=34000.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=111100.0,
        buffer_pool_contribution_tco2e=15720.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0117": AgriculturalCarbonProject(
        project_id="VCS_AG_0117",
        project_title="Regenerative Agriculture Soil Carbon Project #117 (Australia)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Australia",
        total_enrolled_hectares=34250.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=111950.0,
        buffer_pool_contribution_tco2e=15840.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0118": AgriculturalCarbonProject(
        project_id="VCS_AG_0118",
        project_title="Regenerative Agriculture Soil Carbon Project #118 (Canada)",
        standard_registry="Gold Standard Agriculture",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Canada",
        total_enrolled_hectares=34500.0,
        adopted_regenerative_practices=['Alternate Wetting and Drying (AWD) in Rice', 'Direct Seeded Rice (DSR)', 'Organic Manure Biochar'],
        cumulative_verified_carbon_credits_tco2e=112800.0,
        buffer_pool_contribution_tco2e=15960.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0119": AgriculturalCarbonProject(
        project_id="VCS_AG_0119",
        project_title="Regenerative Agriculture Soil Carbon Project #119 (Argentina)",
        standard_registry="Climate Action Reserve Soil",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="Argentina",
        total_enrolled_hectares=34750.0,
        adopted_regenerative_practices=['Controlled Traffic Farming', 'Biochar Soil Amendment', 'Legume Crop Rotations'],
        cumulative_verified_carbon_credits_tco2e=113650.0,
        buffer_pool_contribution_tco2e=16080.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
    "VCS_AG_0120": AgriculturalCarbonProject(
        project_id="VCS_AG_0120",
        project_title="Regenerative Agriculture Soil Carbon Project #120 (United States)",
        standard_registry="Verra VCS (VM0042)",
        methodology_code="VM0042 Methodology for Improved Land Management",
        project_location_country="United States",
        total_enrolled_hectares=35000.0,
        adopted_regenerative_practices=['No-Till Farming', 'Multi-Species Winter Cover Cropping', 'Precision Variable Rate Nitrogen'],
        cumulative_verified_carbon_credits_tco2e=114500.0,
        buffer_pool_contribution_tco2e=16200.0,
        crediting_period_start_year=2021,
        crediting_period_end_year=2041,
    ),
}

def get_carbon_project(project_id: str) -> Optional[AgriculturalCarbonProject]:
    return CARBON_PROJECT_REGISTRY.get(project_id)

def list_all_carbon_projects() -> List[AgriculturalCarbonProject]:
    return list(CARBON_PROJECT_REGISTRY.values())
