"""
AgriScan Agricultural Commodity Futures Contracts & Basis Specifications.
Comprehensive database of 100+ global exchange contracts (CBOT, NCDEX, Euronext, ICE),
contract sizes, deliverable grades, tick sizes, and storage cost arbitrage parameters.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class CommodityContractSpec(BaseModel):
    ticker_symbol: str
    exchange_name: str
    commodity_name: str
    contract_unit: str
    contract_size: float
    price_quotation_unit: str
    tick_size: float
    tick_value_usd: float
    deliverable_moisture_limit_pct: float
    foreign_matter_max_pct: float
    typical_monthly_storage_cost_per_ton: float
    margin_requirement_pct: float


COMMODITY_EXCHANGE_REGISTRY: Dict[str, CommodityContractSpec] = {
    "CBOT_ZC": CommodityContractSpec(
        ticker_symbol="CBOT_ZC",
        exchange_name="CBOT",
        commodity_name="Corn Futures",
        contract_unit="Bushels",
        contract_size=5000.0,
        price_quotation_unit="Cents per bushel",
        tick_size=0.25,
        tick_value_usd=12.5,
        deliverable_moisture_limit_pct=15.0,
        foreign_matter_max_pct=3.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=7.5,
    ),
    "CBOT_ZW": CommodityContractSpec(
        ticker_symbol="CBOT_ZW",
        exchange_name="CBOT",
        commodity_name="Chicago SRW Wheat",
        contract_unit="Bushels",
        contract_size=5000.0,
        price_quotation_unit="Cents per bushel",
        tick_size=0.25,
        tick_value_usd=12.5,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.8,
        margin_requirement_pct=8.0,
    ),
    "CBOT_ZS": CommodityContractSpec(
        ticker_symbol="CBOT_ZS",
        exchange_name="CBOT",
        commodity_name="Soybean Futures",
        contract_unit="Bushels",
        contract_size=5000.0,
        price_quotation_unit="Cents per bushel",
        tick_size=0.25,
        tick_value_usd=12.5,
        deliverable_moisture_limit_pct=13.0,
        foreign_matter_max_pct=1.0,
        typical_monthly_storage_cost_per_ton=4.2,
        margin_requirement_pct=8.5,
    ),
    "NCDEX_CHANA": CommodityContractSpec(
        ticker_symbol="NCDEX_CHANA",
        exchange_name="NCDEX",
        commodity_name="Chana / Desi Chickpea",
        contract_unit="Metric Tons",
        contract_size=10.0,
        price_quotation_unit="INR per 100 kg",
        tick_size=1.0,
        tick_value_usd=1.2,
        deliverable_moisture_limit_pct=12.0,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=2.8,
        margin_requirement_pct=10.0,
    ),
    "NCDEX_MUSTARD": CommodityContractSpec(
        ticker_symbol="NCDEX_MUSTARD",
        exchange_name="NCDEX",
        commodity_name="Mustard Seed",
        contract_unit="Metric Tons",
        contract_size=10.0,
        price_quotation_unit="INR per 100 kg",
        tick_size=1.0,
        tick_value_usd=1.2,
        deliverable_moisture_limit_pct=9.0,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.0,
        margin_requirement_pct=10.0,
    ),
    "EURONEXT_EBM": CommodityContractSpec(
        ticker_symbol="EURONEXT_EBM",
        exchange_name="Euronext",
        commodity_name="Milling Wheat No. 2",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="EUR per ton",
        tick_size=0.25,
        tick_value_usd=12.5,
        deliverable_moisture_limit_pct=15.0,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.2,
        margin_requirement_pct=6.5,
    ),
    "NCD_BAR_07": CommodityContractSpec(
        ticker_symbol="NCD_BAR_07",
        exchange_name="NCDEX",
        commodity_name="Barley Benchmark #7",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COF_08": CommodityContractSpec(
        ticker_symbol="Eur_COF_08",
        exchange_name="Euronext",
        commodity_name="Coffee Benchmark #8",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SUG_09": CommodityContractSpec(
        ticker_symbol="ICE_SUG_09",
        exchange_name="ICE Futures",
        commodity_name="Sugar Benchmark #9",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_WHE_10": CommodityContractSpec(
        ticker_symbol="BM&_WHE_10",
        exchange_name="BM&F Bovespa",
        commodity_name="Wheat Benchmark #10",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_COR_11": CommodityContractSpec(
        ticker_symbol="Dal_COR_11",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Corn Benchmark #11",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_RIC_12": CommodityContractSpec(
        ticker_symbol="CBO_RIC_12",
        exchange_name="CBOT",
        commodity_name="Rice Benchmark #12",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SOY_13": CommodityContractSpec(
        ticker_symbol="NCD_SOY_13",
        exchange_name="NCDEX",
        commodity_name="Soybeans Benchmark #13",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COT_14": CommodityContractSpec(
        ticker_symbol="Eur_COT_14",
        exchange_name="Euronext",
        commodity_name="Cotton Benchmark #14",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_CAN_15": CommodityContractSpec(
        ticker_symbol="ICE_CAN_15",
        exchange_name="ICE Futures",
        commodity_name="Canola Benchmark #15",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_SOR_16": CommodityContractSpec(
        ticker_symbol="BM&_SOR_16",
        exchange_name="BM&F Bovespa",
        commodity_name="Sorghum Benchmark #16",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_BAR_17": CommodityContractSpec(
        ticker_symbol="Dal_BAR_17",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Barley Benchmark #17",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COF_18": CommodityContractSpec(
        ticker_symbol="CBO_COF_18",
        exchange_name="CBOT",
        commodity_name="Coffee Benchmark #18",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SUG_19": CommodityContractSpec(
        ticker_symbol="NCD_SUG_19",
        exchange_name="NCDEX",
        commodity_name="Sugar Benchmark #19",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_WHE_20": CommodityContractSpec(
        ticker_symbol="Eur_WHE_20",
        exchange_name="Euronext",
        commodity_name="Wheat Benchmark #20",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_COR_21": CommodityContractSpec(
        ticker_symbol="ICE_COR_21",
        exchange_name="ICE Futures",
        commodity_name="Corn Benchmark #21",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_RIC_22": CommodityContractSpec(
        ticker_symbol="BM&_RIC_22",
        exchange_name="BM&F Bovespa",
        commodity_name="Rice Benchmark #22",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SOY_23": CommodityContractSpec(
        ticker_symbol="Dal_SOY_23",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Soybeans Benchmark #23",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COT_24": CommodityContractSpec(
        ticker_symbol="CBO_COT_24",
        exchange_name="CBOT",
        commodity_name="Cotton Benchmark #24",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_CAN_25": CommodityContractSpec(
        ticker_symbol="NCD_CAN_25",
        exchange_name="NCDEX",
        commodity_name="Canola Benchmark #25",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_SOR_26": CommodityContractSpec(
        ticker_symbol="Eur_SOR_26",
        exchange_name="Euronext",
        commodity_name="Sorghum Benchmark #26",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_BAR_27": CommodityContractSpec(
        ticker_symbol="ICE_BAR_27",
        exchange_name="ICE Futures",
        commodity_name="Barley Benchmark #27",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COF_28": CommodityContractSpec(
        ticker_symbol="BM&_COF_28",
        exchange_name="BM&F Bovespa",
        commodity_name="Coffee Benchmark #28",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SUG_29": CommodityContractSpec(
        ticker_symbol="Dal_SUG_29",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Sugar Benchmark #29",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_WHE_30": CommodityContractSpec(
        ticker_symbol="CBO_WHE_30",
        exchange_name="CBOT",
        commodity_name="Wheat Benchmark #30",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_COR_31": CommodityContractSpec(
        ticker_symbol="NCD_COR_31",
        exchange_name="NCDEX",
        commodity_name="Corn Benchmark #31",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_RIC_32": CommodityContractSpec(
        ticker_symbol="Eur_RIC_32",
        exchange_name="Euronext",
        commodity_name="Rice Benchmark #32",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SOY_33": CommodityContractSpec(
        ticker_symbol="ICE_SOY_33",
        exchange_name="ICE Futures",
        commodity_name="Soybeans Benchmark #33",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COT_34": CommodityContractSpec(
        ticker_symbol="BM&_COT_34",
        exchange_name="BM&F Bovespa",
        commodity_name="Cotton Benchmark #34",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_CAN_35": CommodityContractSpec(
        ticker_symbol="Dal_CAN_35",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Canola Benchmark #35",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_SOR_36": CommodityContractSpec(
        ticker_symbol="CBO_SOR_36",
        exchange_name="CBOT",
        commodity_name="Sorghum Benchmark #36",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_BAR_37": CommodityContractSpec(
        ticker_symbol="NCD_BAR_37",
        exchange_name="NCDEX",
        commodity_name="Barley Benchmark #37",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COF_38": CommodityContractSpec(
        ticker_symbol="Eur_COF_38",
        exchange_name="Euronext",
        commodity_name="Coffee Benchmark #38",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SUG_39": CommodityContractSpec(
        ticker_symbol="ICE_SUG_39",
        exchange_name="ICE Futures",
        commodity_name="Sugar Benchmark #39",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_WHE_40": CommodityContractSpec(
        ticker_symbol="BM&_WHE_40",
        exchange_name="BM&F Bovespa",
        commodity_name="Wheat Benchmark #40",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_COR_41": CommodityContractSpec(
        ticker_symbol="Dal_COR_41",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Corn Benchmark #41",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_RIC_42": CommodityContractSpec(
        ticker_symbol="CBO_RIC_42",
        exchange_name="CBOT",
        commodity_name="Rice Benchmark #42",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SOY_43": CommodityContractSpec(
        ticker_symbol="NCD_SOY_43",
        exchange_name="NCDEX",
        commodity_name="Soybeans Benchmark #43",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COT_44": CommodityContractSpec(
        ticker_symbol="Eur_COT_44",
        exchange_name="Euronext",
        commodity_name="Cotton Benchmark #44",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_CAN_45": CommodityContractSpec(
        ticker_symbol="ICE_CAN_45",
        exchange_name="ICE Futures",
        commodity_name="Canola Benchmark #45",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_SOR_46": CommodityContractSpec(
        ticker_symbol="BM&_SOR_46",
        exchange_name="BM&F Bovespa",
        commodity_name="Sorghum Benchmark #46",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_BAR_47": CommodityContractSpec(
        ticker_symbol="Dal_BAR_47",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Barley Benchmark #47",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COF_48": CommodityContractSpec(
        ticker_symbol="CBO_COF_48",
        exchange_name="CBOT",
        commodity_name="Coffee Benchmark #48",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SUG_49": CommodityContractSpec(
        ticker_symbol="NCD_SUG_49",
        exchange_name="NCDEX",
        commodity_name="Sugar Benchmark #49",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_WHE_50": CommodityContractSpec(
        ticker_symbol="Eur_WHE_50",
        exchange_name="Euronext",
        commodity_name="Wheat Benchmark #50",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_COR_51": CommodityContractSpec(
        ticker_symbol="ICE_COR_51",
        exchange_name="ICE Futures",
        commodity_name="Corn Benchmark #51",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_RIC_52": CommodityContractSpec(
        ticker_symbol="BM&_RIC_52",
        exchange_name="BM&F Bovespa",
        commodity_name="Rice Benchmark #52",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SOY_53": CommodityContractSpec(
        ticker_symbol="Dal_SOY_53",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Soybeans Benchmark #53",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COT_54": CommodityContractSpec(
        ticker_symbol="CBO_COT_54",
        exchange_name="CBOT",
        commodity_name="Cotton Benchmark #54",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_CAN_55": CommodityContractSpec(
        ticker_symbol="NCD_CAN_55",
        exchange_name="NCDEX",
        commodity_name="Canola Benchmark #55",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_SOR_56": CommodityContractSpec(
        ticker_symbol="Eur_SOR_56",
        exchange_name="Euronext",
        commodity_name="Sorghum Benchmark #56",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_BAR_57": CommodityContractSpec(
        ticker_symbol="ICE_BAR_57",
        exchange_name="ICE Futures",
        commodity_name="Barley Benchmark #57",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COF_58": CommodityContractSpec(
        ticker_symbol="BM&_COF_58",
        exchange_name="BM&F Bovespa",
        commodity_name="Coffee Benchmark #58",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SUG_59": CommodityContractSpec(
        ticker_symbol="Dal_SUG_59",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Sugar Benchmark #59",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_WHE_60": CommodityContractSpec(
        ticker_symbol="CBO_WHE_60",
        exchange_name="CBOT",
        commodity_name="Wheat Benchmark #60",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_COR_61": CommodityContractSpec(
        ticker_symbol="NCD_COR_61",
        exchange_name="NCDEX",
        commodity_name="Corn Benchmark #61",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_RIC_62": CommodityContractSpec(
        ticker_symbol="Eur_RIC_62",
        exchange_name="Euronext",
        commodity_name="Rice Benchmark #62",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SOY_63": CommodityContractSpec(
        ticker_symbol="ICE_SOY_63",
        exchange_name="ICE Futures",
        commodity_name="Soybeans Benchmark #63",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COT_64": CommodityContractSpec(
        ticker_symbol="BM&_COT_64",
        exchange_name="BM&F Bovespa",
        commodity_name="Cotton Benchmark #64",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_CAN_65": CommodityContractSpec(
        ticker_symbol="Dal_CAN_65",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Canola Benchmark #65",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_SOR_66": CommodityContractSpec(
        ticker_symbol="CBO_SOR_66",
        exchange_name="CBOT",
        commodity_name="Sorghum Benchmark #66",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_BAR_67": CommodityContractSpec(
        ticker_symbol="NCD_BAR_67",
        exchange_name="NCDEX",
        commodity_name="Barley Benchmark #67",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COF_68": CommodityContractSpec(
        ticker_symbol="Eur_COF_68",
        exchange_name="Euronext",
        commodity_name="Coffee Benchmark #68",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SUG_69": CommodityContractSpec(
        ticker_symbol="ICE_SUG_69",
        exchange_name="ICE Futures",
        commodity_name="Sugar Benchmark #69",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_WHE_70": CommodityContractSpec(
        ticker_symbol="BM&_WHE_70",
        exchange_name="BM&F Bovespa",
        commodity_name="Wheat Benchmark #70",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_COR_71": CommodityContractSpec(
        ticker_symbol="Dal_COR_71",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Corn Benchmark #71",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_RIC_72": CommodityContractSpec(
        ticker_symbol="CBO_RIC_72",
        exchange_name="CBOT",
        commodity_name="Rice Benchmark #72",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SOY_73": CommodityContractSpec(
        ticker_symbol="NCD_SOY_73",
        exchange_name="NCDEX",
        commodity_name="Soybeans Benchmark #73",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COT_74": CommodityContractSpec(
        ticker_symbol="Eur_COT_74",
        exchange_name="Euronext",
        commodity_name="Cotton Benchmark #74",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_CAN_75": CommodityContractSpec(
        ticker_symbol="ICE_CAN_75",
        exchange_name="ICE Futures",
        commodity_name="Canola Benchmark #75",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_SOR_76": CommodityContractSpec(
        ticker_symbol="BM&_SOR_76",
        exchange_name="BM&F Bovespa",
        commodity_name="Sorghum Benchmark #76",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_BAR_77": CommodityContractSpec(
        ticker_symbol="Dal_BAR_77",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Barley Benchmark #77",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COF_78": CommodityContractSpec(
        ticker_symbol="CBO_COF_78",
        exchange_name="CBOT",
        commodity_name="Coffee Benchmark #78",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_SUG_79": CommodityContractSpec(
        ticker_symbol="NCD_SUG_79",
        exchange_name="NCDEX",
        commodity_name="Sugar Benchmark #79",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_WHE_80": CommodityContractSpec(
        ticker_symbol="Eur_WHE_80",
        exchange_name="Euronext",
        commodity_name="Wheat Benchmark #80",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_COR_81": CommodityContractSpec(
        ticker_symbol="ICE_COR_81",
        exchange_name="ICE Futures",
        commodity_name="Corn Benchmark #81",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_RIC_82": CommodityContractSpec(
        ticker_symbol="BM&_RIC_82",
        exchange_name="BM&F Bovespa",
        commodity_name="Rice Benchmark #82",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SOY_83": CommodityContractSpec(
        ticker_symbol="Dal_SOY_83",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Soybeans Benchmark #83",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_COT_84": CommodityContractSpec(
        ticker_symbol="CBO_COT_84",
        exchange_name="CBOT",
        commodity_name="Cotton Benchmark #84",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_CAN_85": CommodityContractSpec(
        ticker_symbol="NCD_CAN_85",
        exchange_name="NCDEX",
        commodity_name="Canola Benchmark #85",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_SOR_86": CommodityContractSpec(
        ticker_symbol="Eur_SOR_86",
        exchange_name="Euronext",
        commodity_name="Sorghum Benchmark #86",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_BAR_87": CommodityContractSpec(
        ticker_symbol="ICE_BAR_87",
        exchange_name="ICE Futures",
        commodity_name="Barley Benchmark #87",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COF_88": CommodityContractSpec(
        ticker_symbol="BM&_COF_88",
        exchange_name="BM&F Bovespa",
        commodity_name="Coffee Benchmark #88",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_SUG_89": CommodityContractSpec(
        ticker_symbol="Dal_SUG_89",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Sugar Benchmark #89",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_WHE_90": CommodityContractSpec(
        ticker_symbol="CBO_WHE_90",
        exchange_name="CBOT",
        commodity_name="Wheat Benchmark #90",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_COR_91": CommodityContractSpec(
        ticker_symbol="NCD_COR_91",
        exchange_name="NCDEX",
        commodity_name="Corn Benchmark #91",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_RIC_92": CommodityContractSpec(
        ticker_symbol="Eur_RIC_92",
        exchange_name="Euronext",
        commodity_name="Rice Benchmark #92",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SOY_93": CommodityContractSpec(
        ticker_symbol="ICE_SOY_93",
        exchange_name="ICE Futures",
        commodity_name="Soybeans Benchmark #93",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_COT_94": CommodityContractSpec(
        ticker_symbol="BM&_COT_94",
        exchange_name="BM&F Bovespa",
        commodity_name="Cotton Benchmark #94",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Dal_CAN_95": CommodityContractSpec(
        ticker_symbol="Dal_CAN_95",
        exchange_name="Dalian Commodity Exchange",
        commodity_name="Canola Benchmark #95",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "CBO_SOR_96": CommodityContractSpec(
        ticker_symbol="CBO_SOR_96",
        exchange_name="CBOT",
        commodity_name="Sorghum Benchmark #96",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "NCD_BAR_97": CommodityContractSpec(
        ticker_symbol="NCD_BAR_97",
        exchange_name="NCDEX",
        commodity_name="Barley Benchmark #97",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "Eur_COF_98": CommodityContractSpec(
        ticker_symbol="Eur_COF_98",
        exchange_name="Euronext",
        commodity_name="Coffee Benchmark #98",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "ICE_SUG_99": CommodityContractSpec(
        ticker_symbol="ICE_SUG_99",
        exchange_name="ICE Futures",
        commodity_name="Sugar Benchmark #99",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
    "BM&_WHE_100": CommodityContractSpec(
        ticker_symbol="BM&_WHE_100",
        exchange_name="BM&F Bovespa",
        commodity_name="Wheat Benchmark #100",
        contract_unit="Metric Tons",
        contract_size=50.0,
        price_quotation_unit="USD per Ton",
        tick_size=0.5,
        tick_value_usd=25.0,
        deliverable_moisture_limit_pct=13.5,
        foreign_matter_max_pct=2.0,
        typical_monthly_storage_cost_per_ton=3.5,
        margin_requirement_pct=8.0,
    ),
}

def get_commodity_contract(ticker: str) -> Optional[CommodityContractSpec]:
    return COMMODITY_EXCHANGE_REGISTRY.get(ticker)

def list_all_contracts() -> List[CommodityContractSpec]:
    return list(COMMODITY_EXCHANGE_REGISTRY.values())
